logging:
  receivers:
    webapp_logs:
      type: files
      include_paths:
        - /var/log/webapp/webapp.log
      record_log_file_path: true
  processors:
    webapp_processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    level_severity_mapper:
      type: modify_fields
      fields:
        severity:
         move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp_logs]
        processors: [webapp_processor, level_severity_mapper]