name: Packer Format & Validate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  packer-format-and-validate:
    if: github.event_name == 'pull_request' && github.repository == 'CSYE-6225-Cloud-Adarsh-Raj/webapp'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: webapp

    - name: Install Packer
      run: |
        curl -O https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
        unzip -o packer_1.7.4_linux_amd64.zip -d /tmp
        sudo mv /tmp/packer /usr/local/bin

    - name: Debug current working directory
      run: |
        pwd
        ls -la

    - name: List contents of the custom_image directory
      run: ls -la
      working-directory: ./webapp/custom_image

    - name: Packer init
      run: |
        packer init webapp_image.pkr.hcl
      working-directory: ./webapp/custom_image

    - name: Run packer fmt
      run: |
        packer fmt -check -diff webapp_image.pkr.hcl
      id: fmt
      continue-on-error: true
      working-directory: ./webapp/custom_image

    - name: Fail if packer fmt made changes
      if: steps.fmt.outcome == 'failure'
      run: exit 1
      working-directory: ./webapp/custom_image

    - name: List contents of the custom_image directory 1
      run: ls -la
      working-directory: ./webapp/custom_image

    - name: Create dummy binary
      run: |
        mkdir -p ./webapp/dummy
        touch ./webapp/dummy/webapp_dummy
      working-directory: ./webapp

    - name: Debug current working directory 1
      run: |
        pwd
        ls -la
        
    - name: Run packer validate
      run: |
        pwd
        ls -la
        packer validate \
          -var "binary_path=../webapp/dummy/webapp_dummy" \
          webapp_image.pkr.hcl
      working-directory: ./webapp/custom_image
